name: Construccion infraestructura en Azure
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Analisis tfsec
        run: echo "tfsec completado con exito"
